apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-management-deployment
spec:
  selector:
    matchLabels:
      app: hospitalmanagement
  replicas: 2
  template:
    metadata:
      labels:
        app: hospitalmanagement
    spec:
      containers:
        - name: hospitalmanagement-web
          image: pradeepbaipadithaya/devops-assignment-main-web # Image for web service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # Port for the web service
        - name: hospitalmanagement-db
          image: pradeepbaipadithaya/devops-assignment-main-db # Image for database service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306 # Port for the database service

---

apiVersion: v1
kind: Service
metadata:
  name: hospital-management-svc
spec:
  selector:
    app: hospitalmanagement
  ports:
    - protocol: "TCP"
      port: 8081 # Service port
      targetPort: 8080 # Target port of the web service
  type: NodePort
